from __future__ import annotations

import contextlib
import io
import json
import tempfile
import unittest
from pathlib import Path

from dq_questionbank.cli import main

SAMPLE_PATH = Path(__file__).resolve().parents[1] / "examples" / "sample_questions.json"


class CliTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.tmp_path = Path(self.temporary.name)

    def tearDown(self):
        self.temporary.cleanup()

    def test_validate_command_accepts_sample(self):
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = main(["validate", str(SAMPLE_PATH)])
        self.assertEqual(result, 0)
        self.assertIn("Valid:", output.getvalue())

    def test_validate_command_reports_invalid_file(self):
        source = self.tmp_path / "invalid.json"
        source.write_text(
            json.dumps({"id": "set", "title": "Set", "questions": [{"id": "", "stem": ""}]}),
            encoding="utf-8",
        )
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = main(["validate", str(source)])
        self.assertEqual(result, 1)
        self.assertIn("ERROR", output.getvalue())

    def test_convert_json_to_markdown(self):
        output_path = self.tmp_path / "questions.md"
        with contextlib.redirect_stdout(io.StringIO()):
            result = main(["convert", str(SAMPLE_PATH), "--to", "markdown", "-o", str(output_path)])
        self.assertEqual(result, 0)
        self.assertTrue(output_path.read_text(encoding="utf-8").startswith("<!-- Generated by DQ"))

    def test_missing_input_returns_usage_error(self):
        error = io.StringIO()
        with contextlib.redirect_stderr(error):
            result = main(["validate", str(self.tmp_path / "missing.json")])
        self.assertEqual(result, 2)
        self.assertIn("not found", error.getvalue())
