"""Database-neutral tools for structured educational questions."""

from .asset_repair import (
    AssetRepairProposal,
    bind_asset_repair,
    preview_asset_repair,
)
from .coding_agent_workfile import (
    CODING_AGENT_WORKFILE_SCHEMA,
    FORBIDDEN_WORKFILE_FIELDS,
    TEXT_FIELDS,
    WORK_STATUS_NEEDS_REVIEW,
    WORK_STATUS_PENDING,
    WORK_STATUS_TRANSCRIBED,
    WORK_STATUSES,
    read_work_file,
    transition_work_status,
    validate_work_file,
    write_work_file,
)
from .exceptions import (
    FormatDetectionError,
    FormatError,
    FormatLoadError,
    FormatWriteError,
    ImportBundleError,
    PluginDiscoveryError,
    QuestionBankError,
    SchemaError,
    SchemaNotFoundError,
    SchemaValidationError,
    SchemaVersionError,
    StaleFindingError,
)
from .formula_images import (
    FORMULA_IMAGE_FLAG,
    FormulaImageCandidate,
    detect_formula_image_candidates,
    fill_transcription,
)
from .intake import (
    ImportCase,
    export_reviewed_questions,
    get_import_case,
    list_import_cases,
    prepare_import_bundle,
    prepare_import_case,
    review_import_session,
    run_import_case,
)
from .interfaces import AIProvider, QuestionExporter, QuestionImporter, StorageAdapter
from .latex_compat import (
    DEGRADED_PAIR_STATS_KEY,
    DIFFERENTIAL_STATS_KEY,
    is_relation_expression,
    normalize_integral_differentials,
    restore_degraded_relation_pairs,
)
from .latex_repair import (
    LatexRepairOutcome,
    repair_bare_function_names,
    repair_delimiter_spacing,
    repair_latex_braces,
    repair_latex_source,
    repair_operator_spacing,
)
from .mapping_import import (
    FieldMapping,
    apply_mapping,
    load_mapping,
)
from .migration import list_migrations, migrate, register_migration
from .models import (
    LATEST_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    Answer,
    Asset,
    Choice,
    Content,
    ContentBlock,
    Question,
    QuestionSet,
    SourceMetadata,
    TaxonomyRef,
)
from .omml_import import (
    OmmlFormula,
    parse_omml_element,
    read_docx_math,
)
from .pdf_identity import job_matches_tag, normalize_import_tag
from .pdf_metadata import (
    PAPER_QUESTION_TYPES,
    PDF_METADATA_SCHEMA,
    PaperMetadataError,
    assert_metadata_matches,
    canonical_paper_metadata,
    metadata_from_questions,
)
from .pdf_postflight import POSTFLIGHT_REPORT_SCHEMA, scan_candidate_dir
from .plugins import PLUGIN_ENTRY_POINT_GROUP, available_plugins, discover_plugins
from .quality_findings import (
    DECISIONS,
    RULESET_VERSION,
    SEVERITIES,
    QualityFinding,
    QualityJudgment,
    detect_quality_findings,
    field_fingerprint,
    finding_state,
    judge_finding,
)
from .registry import FormatRegistry, default_registry
from .review_session import (
    DECISION_ACCEPTED,
    DECISION_PENDING,
    DECISION_REJECTED,
    ImportCandidate,
    ImportCandidateSession,
)
from .schema import load_schema, schema_path
from .sqlite_storage import SqliteStorageAdapter
from .storage import FilesystemStorageAdapter
from .validation import (
    ValidationIssue,
    validate_question,
    validate_question_set,
    validate_with_schema,
)
from .word_macro_id import (
    FULL_ID_PREFIX,
    RESERVED_TOKENS,
    SUBJECT_TOKENS,
    WordMacroIdMemory,
    expand_question_spec,
    is_year_token,
    normalize_spec_separators,
)
from .word_publishing import (
    ENVELOPE_VERSION,
    BlockResult,
    WordPublisher,
    WordPublishingBridge,
    WordPublishingError,
    build_envelope,
    canonical_json,
    export_word_publishing,
    extract_managed_blocks,
    question_fingerprint,
    validate_envelope,
    word_macro_source,
)

__all__ = [
    "FormatDetectionError",
    "FormatError",
    "FormatLoadError",
    "FormatWriteError",
    "ImportBundleError",
    "ImportCase",
    "PluginDiscoveryError",
    "QuestionBankError",
    "FormatRegistry",
    "FilesystemStorageAdapter",
    "SqliteStorageAdapter",
    "DECISION_ACCEPTED",
    "DECISION_PENDING",
    "DECISION_REJECTED",
    "ImportCandidate",
    "ImportCandidateSession",
    "PLUGIN_ENTRY_POINT_GROUP",
    "SchemaError",
    "SchemaNotFoundError",
    "SchemaValidationError",
    "SchemaVersionError",
    "StaleFindingError",
    "AssetRepairProposal",
    "bind_asset_repair",
    "preview_asset_repair",
    "FORMULA_IMAGE_FLAG",
    "FormulaImageCandidate",
    "detect_formula_image_candidates",
    "fill_transcription",
    "Answer",
    "Asset",
    "Choice",
    "Content",
    "ContentBlock",
    "Question",
    "QuestionSet",
    "QuestionExporter",
    "QuestionImporter",
    "SourceMetadata",
    "StorageAdapter",
    "TaxonomyRef",
    "OmmlFormula",
    "parse_omml_element",
    "read_docx_math",
    "FieldMapping",
    "apply_mapping",
    "load_mapping",
    "AIProvider",
    "ValidationIssue",
    "list_migrations",
    "load_schema",
    "available_plugins",
    "default_registry",
    "discover_plugins",
    "migrate",
    "register_migration",
    "schema_path",
    "LATEST_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "validate_question",
    "validate_question_set",
    "validate_with_schema",
    "export_reviewed_questions",
    "get_import_case",
    "list_import_cases",
    "prepare_import_bundle",
    "prepare_import_case",
    "review_import_session",
    "run_import_case",
    "LatexRepairOutcome",
    "repair_bare_function_names",
    "repair_delimiter_spacing",
    "repair_latex_braces",
    "repair_latex_source",
    "repair_operator_spacing",
    "DECISIONS",
    "RULESET_VERSION",
    "SEVERITIES",
    "QualityFinding",
    "QualityJudgment",
    "detect_quality_findings",
    "field_fingerprint",
    "finding_state",
    "judge_finding",
    "ENVELOPE_VERSION",
    "BlockResult",
    "WordPublisher",
    "WordPublishingBridge",
    "WordPublishingError",
    "build_envelope",
    "canonical_json",
    "export_word_publishing",
    "extract_managed_blocks",
    "question_fingerprint",
    "validate_envelope",
    "word_macro_source",
    "CODING_AGENT_WORKFILE_SCHEMA",
    "FORBIDDEN_WORKFILE_FIELDS",
    "TEXT_FIELDS",
    "WORK_STATUSES",
    "WORK_STATUS_NEEDS_REVIEW",
    "WORK_STATUS_PENDING",
    "WORK_STATUS_TRANSCRIBED",
    "read_work_file",
    "transition_work_status",
    "validate_work_file",
    "write_work_file",
    "DEGRADED_PAIR_STATS_KEY",
    "DIFFERENTIAL_STATS_KEY",
    "is_relation_expression",
    "normalize_integral_differentials",
    "restore_degraded_relation_pairs",
    "PAPER_QUESTION_TYPES",
    "PDF_METADATA_SCHEMA",
    "PaperMetadataError",
    "assert_metadata_matches",
    "canonical_paper_metadata",
    "metadata_from_questions",
    "POSTFLIGHT_REPORT_SCHEMA",
    "scan_candidate_dir",
    "job_matches_tag",
    "normalize_import_tag",
    "FULL_ID_PREFIX",
    "RESERVED_TOKENS",
    "SUBJECT_TOKENS",
    "WordMacroIdMemory",
    "expand_question_spec",
    "is_year_token",
    "normalize_spec_separators",
]

__version__ = "1.1.0"
