"""Readable Markdown representation with deterministic round-trip markers."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from ..models import Choice, Question, QuestionSet
from .common import content_to_markup, markup_to_content

QUESTION_HEADER_RE = re.compile(r"^## Question `(?P<id>[^`]+)` \((?P<type>[^)]+)\)$")
CHOICE_RE = re.compile(r"^- \[(?P<id>[^]]+)\] (?P<content>.*)$")


def _json_line(prefix: str, value: Any) -> str:
    return f"{prefix}{json.dumps(value, ensure_ascii=False, separators=(',', ':'))}"


class MarkdownExporter:
    format_name = "markdown"
    extensions = (".md", ".markdown")

    def dump(self, question_set: QuestionSet, target: Path, **options: Any) -> None:
        lines = [
            "<!-- Generated by DQ QuestionBank Core. "
            "Machine markers enable deterministic import. -->",
            f"# {question_set.title}",
            "",
            _json_line(
                "<!-- dq:set ",
                {
                    "schema_version": question_set.schema_version,
                    "id": question_set.id,
                    "language": question_set.language,
                    "description": question_set.description,
                    "metadata": question_set.metadata,
                },
            )
            + " -->",
            "",
        ]
        if question_set.description:
            lines.extend([question_set.description, ""])
        for question in question_set.questions:
            lines.extend(self._question_lines(question, 2))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")

    def _question_lines(self, question: Question, level: int) -> list[str]:
        heading = "#" * level
        metadata = question.to_dict()
        for key in ("stem", "choices", "answer", "solution", "hints"):
            metadata.pop(key, None)
        lines = [
            f"{heading} Question `{question.id}` ({question.type})",
            _json_line("<!-- dq:question ", metadata) + " -->",
            "",
            content_to_markup(question.stem),
            "",
        ]
        if question.choices:
            lines.append(f"{'#' * (level + 1)} Choices")
            for choice in question.choices:
                lines.append(f"- [{choice.id}] {content_to_markup(choice.content)}")
            lines.append("")
        if question.answer:
            lines.extend(
                [f"**Answer:** `{json.dumps(question.answer.to_dict(), ensure_ascii=False)}`", ""]
            )
        if question.solution:
            lines.extend(
                [f"{'#' * (level + 1)} Solution", content_to_markup(question.solution), ""]
            )
        for index, hint in enumerate(question.hints, start=1):
            lines.extend([f"{'#' * (level + 1)} Hint {index}", content_to_markup(hint), ""])
        return lines


class MarkdownImporter:
    format_name = "markdown"
    extensions = (".md", ".markdown")

    def load(self, source: Path, **options: Any) -> QuestionSet:
        lines = source.read_text(encoding="utf-8-sig").splitlines()
        set_meta: dict[str, Any] = {}
        questions: list[Question] = []
        current: dict[str, Any] | None = None
        section = "stem"
        buffers: dict[str, list[str]] = {}

        def finish() -> None:
            nonlocal current, buffers
            if current is None:
                return
            current["stem"] = markup_to_content(
                "\n".join(buffers.get("stem", [])).strip()
            ).to_dict()
            if buffers.get("solution"):
                current["solution"] = markup_to_content(
                    "\n".join(buffers["solution"]).strip()
                ).to_dict()
            hints = [
                markup_to_content("\n".join(value).strip()).to_dict()
                for key, value in sorted(buffers.items())
                if key.startswith("hint:")
            ]
            if hints:
                current["hints"] = hints
            questions.append(Question.from_dict(current))
            current = None
            buffers = {}

        for line in lines:
            stripped = line.strip()
            if stripped.startswith("<!-- dq:set ") and stripped.endswith(" -->"):
                set_meta = json.loads(stripped[len("<!-- dq:set ") : -len(" -->")])
                continue
            header = QUESTION_HEADER_RE.match(stripped)
            if header:
                finish()
                current = {"id": header.group("id"), "type": header.group("type")}
                buffers = {"stem": []}
                section = "stem"
                continue
            if current is None:
                continue
            if stripped.startswith("<!-- dq:question ") and stripped.endswith(" -->"):
                current.update(json.loads(stripped[len("<!-- dq:question ") : -len(" -->")]))
                continue
            if stripped.endswith(" Choices") and stripped.startswith("#"):
                section = "choices"
                current.setdefault("choices", [])
                continue
            if stripped.endswith(" Solution") and stripped.startswith("#"):
                section = "solution"
                buffers.setdefault("solution", [])
                continue
            hint_match = re.match(r"^#+ Hint (\d+)$", stripped)
            if hint_match:
                section = f"hint:{int(hint_match.group(1)):04d}"
                buffers.setdefault(section, [])
                continue
            if stripped.startswith("**Answer:** `") and stripped.endswith("`"):
                current["answer"] = json.loads(stripped[len("**Answer:** `") : -1])
                continue
            if section == "choices":
                choice_match = CHOICE_RE.match(line)
                if choice_match:
                    choice = Choice(
                        choice_match.group("id"), markup_to_content(choice_match.group("content"))
                    )
                    current["choices"].append(choice.to_dict())
                continue
            buffers.setdefault(section, []).append(line)
        finish()
        title = next(
            (line[2:].strip() for line in lines if line.startswith("# ")), "Imported questions"
        )
        return QuestionSet.from_dict(
            {
                "schema_version": set_meta.get("schema_version", "1.0"),
                "id": set_meta.get("id", source.stem),
                "title": title,
                "language": set_meta.get("language", "en"),
                "description": set_meta.get("description"),
                "metadata": set_meta.get("metadata", {}),
                "questions": [question.to_dict() for question in questions],
            }
        )
